print("Arithmatic Operation")
print("********")
a=int(input("Enter a value: "))
b=int(input("Enter b value: "))
print("********")
print("Addition :",a+b)
print("Subraction :",a-b)
print("Multiplicaton :",a*b)
print("Division :",a//b)
print("Remainder :",a%b)
